### PR TITLE
[JENKINS-16284] re-implement plugin in java

### PR DESCRIPTION
**Pull request by ndeloof**
I have no idea how to fix ruby binding issue detected on JENKINS-16284
For such a trivial plugin was simpler for me to translate / re-implement in Java

### CODE REVIEW

**Comment by ndeloof** [comment]
@reviewbybees

**Comment by olivergondza** [comment]
@ndeloof, this plugin seems to some extent replicate what [mail watcher plugin](https://wiki.jenkins-ci.org/display/JENKINS/Mail+Watcher+Plugin‎) does.

**Comment by ndeloof** [comment]
indeed, I didn't know this one. So seems node-offline-notification-plugin should just be deprecated

**Comment by jtnord** [comment]
@ndeloof given this plugin is now marked as deprecated can this request be closed?

**Pull request closed without merging**
